import type { FallbackOpportunity } from "./staticFallbacks";

/** Active hackathons verified against their live Devpost pages on 2026-08-15. */
export const ISSUE_536_VERIFIED_HACKATHONS: FallbackOpportunity[] = [
  {
    id: "opp_2026_h01",
    title: "Build with Gemini XPRIZE",
    type: "Hackathon",
    organization: "XPRIZE / Google",
    tags: ["AI", "Gemini", "Innovation", "Students"],
    deadline: "2026-08-17T13:00:00-07:00",
    apply_link: "https://xprize.devpost.com/",
    description: "Global hackathon challenging builders to create products with Gemini that have meaningful real-world impact.",
    location: "Online / Global",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://xprize.devpost.com/rules", reviewerNotes: "Official Devpost rules show submissions remain open through August 17, 2026." }
  },
  {
    id: "opp_2026_h02",
    title: "Pixel Forge AI Hackathon",
    type: "Hackathon",
    organization: "Pixel Forge",
    tags: ["AI", "Web", "Open Source", "Beginners"],
    deadline: "2026-08-22T23:59:00Z",
    apply_link: "https://pixel-forge-ai-hackathon-08.devpost.com/",
    description: "AI hackathon for building web or application projects with meaningful AI integration and open-source submissions.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://pixel-forge-ai-hackathon-08.devpost.com/rules" }
  },
  {
    id: "opp_2026_h03",
    title: "NeuralSprint",
    type: "Hackathon",
    organization: "NeuralSprint",
    tags: ["AI", "Machine Learning", "Web", "Social Good"],
    deadline: "2026-08-23T23:45:00-07:00",
    apply_link: "https://neuralsprint.devpost.com/",
    description: "Student online hackathon focused on building novel technology solutions across AI, web and social-good themes.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://neuralsprint.devpost.com/details/dates" }
  },
  {
    id: "opp_2026_h04",
    title: "Africa Deep Tech Challenge 2026",
    type: "Hackathon",
    organization: "Africa Deep Tech Challenge",
    tags: ["AI", "LLM", "Edge AI", "Deep Tech"],
    deadline: "2026-08-24T23:45:00-07:00",
    apply_link: "https://adtc-2026.devpost.com/",
    description: "Deep-tech challenge focused on efficient on-device language models and AI for hardware-constrained environments.",
    location: "Online / Global",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://adtc-2026.devpost.com/details/dates" }
  },
  {
    id: "opp_2026_h05",
    title: "AI Builders Hackathon",
    type: "Hackathon",
    organization: "OSC",
    tags: ["AI", "Machine Learning", "Students", "Open Ended"],
    deadline: "2026-08-25T23:59:00Z",
    apply_link: "https://ai-builders-hackathon-2026.devpost.com/",
    description: "Student-friendly AI hackathon for designing, building and testing intelligent systems and AI-powered solutions.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://ai-builders-hackathon-2026.devpost.com/rules" }
  },
  {
    id: "opp_2026_h06",
    title: "The Great Agent Hackathon",
    type: "Hackathon",
    organization: "Women In Product India / Freshworks",
    tags: ["AI Agents", "Enterprise", "Freshworks", "India"],
    deadline: "2026-08-25T23:45:00+05:30",
    apply_link: "https://the-great-agent-hackathon.devpost.com/",
    description: "Two-stage hackathon focused on enterprise AI agents, with an online qualification round and an in-person Bangalore build for shortlisted teams.",
    location: "Bangalore, India / Online qualification",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://the-great-agent-hackathon.devpost.com/" }
  },
  {
    id: "opp_2026_h07",
    title: "Galuxium Nexus V2",
    type: "Hackathon",
    organization: "Galuxium",
    tags: ["AI", "SaaS", "Automation", "Startups"],
    deadline: "2026-08-31T17:00:00+05:30",
    apply_link: "https://galuxium-nexus-v2-29411.devpost.com/",
    description: "Build and launch SaaS products around AI, creators and automation with a focus on real users and practical value.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://galuxium-nexus-v2-29411.devpost.com/details/dates" }
  },
  {
    id: "opp_2026_h08",
    title: "Hacksocial 2026",
    type: "Hackathon",
    organization: "Hacksocial",
    tags: ["AI", "Social Good", "Students", "Open Ended"],
    deadline: "2026-08-31T23:59:00Z",
    apply_link: "https://hacksocial2026.devpost.com/",
    description: "Student online hackathon encouraging technology projects designed to benefit communities and the greater good.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://hacksocial2026.devpost.com/" }
  },
  {
    id: "opp_2026_h09",
    title: "AI YES: International Youth AI Competition",
    type: "Hackathon",
    organization: "International AI Youth Education Society",
    tags: ["AI", "Youth", "Education", "Students"],
    deadline: "2026-09-01T12:00:00-07:00",
    apply_link: "https://ai-yes-competition-30441.devpost.com/",
    description: "International youth AI competition for student teams building beginner-friendly AI projects.",
    location: "Online / Global",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://ai-yes-competition-30441.devpost.com/" }
  },
  {
    id: "opp_2026_h10",
    title: "VoltHacks",
    type: "Hackathon",
    organization: "VoltHacks",
    tags: ["AI", "Web", "Open Ended", "Beginners"],
    deadline: "2026-09-05T17:00:00-04:00",
    apply_link: "https://volthacks.devpost.com/",
    description: "Worldwide online hackathon open to participants age 13 and older, including beginners, with technology and innovation challenges.",
    location: "Online / Worldwide",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://volthacks.devpost.com/details/dates" }
  },
  {
    id: "opp_2026_h11",
    title: "Syntax Summit",
    type: "Hackathon",
    organization: "Student Organization",
    tags: ["DevOps", "AI", "Programming Languages", "Students"],
    deadline: "2026-09-05T17:00:00+05:00",
    apply_link: "https://syntax-summit.devpost.com/",
    description: "Student hackathon challenging participants to design domain-specific languages, parsers, interpreters or compilers.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://syntax-summit.devpost.com/" }
  },
  {
    id: "opp_2026_h12",
    title: "Agentic Cinema: The Blockbuster Hackathon",
    type: "Hackathon",
    organization: "Google Cloud Partnerships",
    tags: ["AI Agents", "Google Cloud", "Media", "Enterprise"],
    deadline: "2026-09-07T14:00:00-07:00",
    apply_link: "https://agentic-cinema.devpost.com/",
    description: "Google Cloud hackathon challenging builders to create production-ready AI agents or multi-agent networks for filmmaking and entertainment workflows.",
    location: "Online / Global",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://agentic-cinema.devpost.com/rules" }
  },
  {
    id: "opp_2026_h13",
    title: "VentureFix",
    type: "Hackathon",
    organization: "PropNote AI",
    tags: ["Startups", "AI", "Product", "Entrepreneurship"],
    deadline: "2026-09-13T23:59:00Z",
    apply_link: "https://venturefix.devpost.com/",
    description: "Student hackathon with Venture Build and Venture Pitch tracks for solving real business problems through technology or entrepreneurship.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://venturefix.devpost.com/" }
  },
  {
    id: "opp_2026_h14",
    title: "CALL-E: Your Code Is Calling",
    type: "Hackathon",
    organization: "CALL-E",
    tags: ["AI Agents", "Voice AI", "Communication", "Enterprise"],
    deadline: "2026-09-14T23:45:00+08:00",
    apply_link: "https://call-e.devpost.com/",
    description: "Build an AI agent that can make real phone calls and demonstrate practical voice-agent workflows.",
    location: "Online / Global",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://call-e.devpost.com/rules" }
  },
  {
    id: "opp_2026_h15",
    title: "OneAquaHealth IEEE Global Hackathon",
    type: "Hackathon",
    organization: "IEEE OneAquaHealth",
    tags: ["AI", "Health", "Environment", "Social Good"],
    deadline: "2026-08-31T23:59:00Z",
    apply_link: "https://oneaquahealth-ieee-hackathon.devpost.com/",
    description: "Global student hackathon focused on sustainable and healthy urban freshwater ecosystems using technology and citizen science.",
    location: "Online / Global",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://oneaquahealth-ieee-hackathon.devpost.com/rules", reviewerNotes: "Registration closes August 31; hackathon runs September 16-30, 2026." }
  },
  {
    id: "opp_2026_h16",
    title: "GatewayHacks 2026 | Software & AI",
    type: "Hackathon",
    organization: "GatewayGS",
    tags: ["Software", "AI", "Social Good", "Students"],
    deadline: "2026-10-02T23:59:00Z",
    apply_link: "https://gatewayhacks-2026.devpost.com/",
    description: "Student online hackathon for building software, applications and AI solutions aimed at practical positive impact.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://gatewayhacks-2026.devpost.com/" }
  },
  {
    id: "opp_2026_h17",
    title: "SC Quantathon v3",
    type: "Hackathon",
    organization: "Clemson Quantum",
    tags: ["Quantum", "Machine Learning", "Students", "Innovation"],
    deadline: "2026-09-27T10:00:00-04:00",
    apply_link: "https://sc-quantathon-v3.devpost.com/",
    description: "Student-led quantum hackathon at Clemson University focused on hands-on problem solving and industry-connected quantum technology.",
    location: "Clemson, South Carolina, USA",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://sc-quantathon-v3.devpost.com/details/dates" }
  },
  {
    id: "opp_2026_h18",
    title: "MunichTech EXPO Hackathon",
    type: "Hackathon",
    organization: "MunichTech EXPO",
    tags: ["AI", "Industry 4.0", "Sustainability", "Productivity"],
    deadline: "2026-09-20T17:00:00+02:00",
    apply_link: "https://munichtech-expo.devpost.com/",
    description: "Europe-focused innovation challenge covering applied AI, digital sovereignty, industry, health, sustainability and enterprise software.",
    location: "Munich, Germany",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://munichtech-expo.devpost.com/details/dates" }
  },
  {
    id: "opp_2026_h19",
    title: "Global Innovation Build Challenge V2",
    type: "Hackathon",
    organization: "Kang Chiao International School Student",
    tags: ["AI", "Innovation", "Students", "Social Good"],
    deadline: "2026-09-21T23:45:00-06:00",
    apply_link: "https://gibc-v2.devpost.com/",
    description: "Student-only online invention challenge with tracks including foundational LLM development and technology for social good.",
    location: "Online / Global",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://gibc-v2.devpost.com/" }
  },
  {
    id: "opp_2026_h20",
    title: "LUMA Hackathon",
    type: "Hackathon",
    organization: "LUMA",
    tags: ["AI", "Machine Learning", "Students", "Beginner Friendly"],
    deadline: "2026-09-28T17:00:00-04:00",
    apply_link: "https://luma-hackathon-fall.devpost.com/",
    description: "Online student hackathon beginning September 20, 2026, designed for young participants building AI and open-ended projects.",
    location: "Online / Global",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://luma-hackathon-fall.devpost.com/" }
  }
];
