import type { FallbackOpportunity } from "./staticFallbacks";

/**
 * Issue #536: curated opportunities checked on 2026-08-15.
 * Sources are official program/application pages or established opportunity
 * platforms. Entries are intentionally kept explicit so they can be audited.
 */
export const ISSUE_536_OPPORTUNITIES: FallbackOpportunity[] = [
  {
    id: "opp_2026_001",
    title: "Microsoft Imagine Cup",
    type: "Hackathon",
    organization: "Microsoft",
    tags: ["AI", "Cloud", "Innovation", "Students"],
    deadline: "2026-08-31",
    apply_link: "https://imaginecup.microsoft.com/",
    description: "Global student technology competition focused on building innovative solutions with Microsoft technologies.",
    location: "Global / Online",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://imaginecup.microsoft.com/" }
  },
  {
    id: "opp_2026_002",
    title: "MLH Global Hack Week",
    type: "Hackathon",
    organization: "Major League Hacking",
    tags: ["Hackathon", "Open Source", "Students", "Workshops"],
    deadline: "Rolling",
    apply_link: "https://www.mlh.com/events",
    description: "Recurring online hackathon and workshop series for student developers and the wider developer community.",
    location: "Online",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.mlh.com/events" }
  },
  {
    id: "opp_2026_003",
    title: "Devpost Hackathons",
    type: "Hackathon",
    organization: "Devpost",
    tags: ["Hackathon", "AI", "Web Development", "Students"],
    deadline: "Rolling",
    apply_link: "https://devpost.com/hackathons",
    description: "Active directory of online and in-person technology hackathons from companies, universities and communities.",
    location: "Global / Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://devpost.com/hackathons" }
  },
  {
    id: "opp_2026_004",
    title: "GitHub Student Developer Pack",
    type: "Student Program",
    organization: "GitHub",
    tags: ["GitHub", "Developer Tools", "Students", "Open Source"],
    deadline: "Rolling",
    apply_link: "https://education.github.com/pack",
    description: "Student benefit program providing access to developer tools, learning resources and partner offers.",
    location: "Global / Online",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://education.github.com/pack" }
  },
  {
    id: "opp_2026_005",
    title: "GitHub Campus Experts",
    type: "Fellowship",
    organization: "GitHub",
    tags: ["Community", "GitHub", "Leadership", "Students"],
    deadline: "Rolling",
    apply_link: "https://education.github.com/experts",
    description: "Community leadership program that trains students to build and lead developer communities on campus.",
    location: "Global / Online",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://education.github.com/experts" }
  },
  {
    id: "opp_2026_006",
    title: "Google Cloud Innovators",
    type: "Student Program",
    organization: "Google Cloud",
    tags: ["Cloud", "Google", "Learning", "Community"],
    deadline: "Rolling",
    apply_link: "https://cloud.google.com/innovators",
    description: "Google Cloud community and learning ecosystem for developers and technology learners.",
    location: "Global / Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://cloud.google.com/innovators" }
  },
  {
    id: "opp_2026_007",
    title: "Google Cloud Skills Boost",
    type: "Learning Program",
    organization: "Google Cloud",
    tags: ["Cloud", "Google", "Training", "Certificates"],
    deadline: "Rolling",
    apply_link: "https://www.cloudskillsboost.google/",
    description: "Hands-on Google Cloud learning paths and labs covering cloud infrastructure, data and AI.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.cloudskillsboost.google/" }
  },
  {
    id: "opp_2026_008",
    title: "AWS Educate",
    type: "Student Program",
    organization: "Amazon Web Services",
    tags: ["AWS", "Cloud", "Students", "Learning"],
    deadline: "Rolling",
    apply_link: "https://aws.amazon.com/education/awseducate/",
    description: "Free cloud-learning resources and career-oriented training for students and educators.",
    location: "Global / Online",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://aws.amazon.com/education/awseducate/" }
  },
  {
    id: "opp_2026_009",
    title: "Oracle Academy",
    type: "Student Program",
    organization: "Oracle",
    tags: ["Java", "Database", "Cloud", "Students"],
    deadline: "Rolling",
    apply_link: "https://academy.oracle.com/",
    description: "Academic technology program offering learning resources in Java, databases, cloud and related technologies.",
    location: "Global / Online",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://academy.oracle.com/" }
  },
  {
    id: "opp_2026_010",
    title: "Microsoft Learn Student Hub",
    type: "Learning Program",
    organization: "Microsoft",
    tags: ["Azure", "AI", "Cloud", "Students"],
    deadline: "Rolling",
    apply_link: "https://learn.microsoft.com/training/students/",
    description: "Microsoft learning resources and student-focused pathways for cloud, AI and developer technologies.",
    location: "Online",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://learn.microsoft.com/training/students/" }
  },
  {
    id: "opp_2026_011",
    title: "Microsoft for Startups Founders Hub",
    type: "Startup Program",
    organization: "Microsoft",
    tags: ["Startups", "Azure", "AI", "Entrepreneurship"],
    deadline: "Rolling",
    apply_link: "https://www.microsoft.com/en-us/startups",
    description: "Startup support ecosystem providing technology, cloud resources and learning opportunities to eligible founders.",
    location: "Global / Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.microsoft.com/en-us/startups" }
  },
  {
    id: "opp_2026_012",
    title: "NVIDIA Deep Learning Institute",
    type: "Learning Program",
    organization: "NVIDIA",
    tags: ["AI", "Machine Learning", "GPU", "Deep Learning"],
    deadline: "Rolling",
    apply_link: "https://www.nvidia.com/en-us/training/",
    description: "Hands-on technical training and learning resources covering accelerated computing, AI and deep learning.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.nvidia.com/en-us/training/" }
  },
  {
    id: "opp_2026_013",
    title: "NVIDIA Academic Programs",
    type: "Student Program",
    organization: "NVIDIA",
    tags: ["AI", "GPU", "Research", "Students"],
    deadline: "Rolling",
    apply_link: "https://www.nvidia.com/en-us/industries/higher-education/",
    description: "Academic ecosystem supporting research, teaching and student learning around accelerated computing and AI.",
    location: "Global / Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.nvidia.com/en-us/industries/higher-education/" }
  },
  {
    id: "opp_2026_014",
    title: "IBM SkillsBuild",
    type: "Learning Program",
    organization: "IBM",
    tags: ["AI", "Cloud", "Cybersecurity", "Students"],
    deadline: "Rolling",
    apply_link: "https://skillsbuild.org/",
    description: "Free learning platform with technology courses, credentials and career preparation resources.",
    location: "Online",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://skillsbuild.org/" }
  },
  {
    id: "opp_2026_015",
    title: "Cisco Networking Academy",
    type: "Learning Program",
    organization: "Cisco",
    tags: ["Networking", "Cybersecurity", "Python", "Students"],
    deadline: "Rolling",
    apply_link: "https://www.netacad.com/",
    description: "Online technology education platform covering networking, cybersecurity, programming and digital skills.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.netacad.com/" }
  },
  {
    id: "opp_2026_016",
    title: "Salesforce Trailhead",
    type: "Learning Program",
    organization: "Salesforce",
    tags: ["Cloud", "CRM", "AI", "Learning"],
    deadline: "Rolling",
    apply_link: "https://trailhead.salesforce.com/",
    description: "Gamified learning platform for Salesforce, cloud, data, AI and career skills.",
    location: "Online",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://trailhead.salesforce.com/" }
  },
  {
    id: "opp_2026_017",
    title: "Red Hat Academy",
    type: "Student Program",
    organization: "Red Hat",
    tags: ["Linux", "Cloud", "Open Source", "Students"],
    deadline: "Rolling",
    apply_link: "https://www.redhat.com/en/services/training/red-hat-academy",
    description: "Academic training ecosystem focused on Linux, open source and enterprise technologies.",
    location: "Global / Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.redhat.com/en/services/training/red-hat-academy" }
  },
  {
    id: "opp_2026_018",
    title: "Linux Foundation Training",
    type: "Learning Program",
    organization: "Linux Foundation",
    tags: ["Linux", "Open Source", "Cloud", "Kubernetes"],
    deadline: "Rolling",
    apply_link: "https://training.linuxfoundation.org/",
    description: "Professional and community learning programs covering Linux and major open-source technologies.",
    location: "Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://training.linuxfoundation.org/" }
  },
  {
    id: "opp_2026_019",
    title: "CNCF LFX Mentorship",
    type: "Mentorship",
    organization: "Cloud Native Computing Foundation",
    tags: ["Open Source", "Kubernetes", "Cloud", "Mentorship"],
    deadline: "Rolling cohorts",
    apply_link: "https://mentorship.lfx.linuxfoundation.org/",
    description: "Mentorship opportunities for contributors working with Linux Foundation and cloud-native open-source projects.",
    location: "Global / Remote",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://mentorship.lfx.linuxfoundation.org/" }
  },
  {
    id: "opp_2026_020",
    title: "Outreachy",
    type: "Internship",
    organization: "Outreachy",
    tags: ["Open Source", "Remote", "Internship", "Diversity"],
    deadline: "Rolling cohorts",
    apply_link: "https://www.outreachy.org/apply/",
    description: "Paid remote internships contributing to open source and free software projects.",
    location: "Remote",
    isLive: true,
    applicationFee: { isFree: true, amount: 0, currency: "USD" },
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.outreachy.org/apply/" }
  },
  {
    id: "opp_2026_021",
    title: "Season of KDE",
    type: "Open Source Program",
    organization: "KDE",
    tags: ["Open Source", "KDE", "Software Development", "Students"],
    deadline: "Annual / Check current cycle",
    apply_link: "https://season.kde.org/",
    description: "KDE community program offering contributors opportunities to work on open-source software and community projects.",
    location: "Global / Remote",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://season.kde.org/" }
  },
  {
    id: "opp_2026_022",
    title: "Google Summer of Code",
    type: "Open Source Program",
    organization: "Google",
    tags: ["Open Source", "Software Development", "Mentorship", "Students"],
    deadline: "Annual program",
    apply_link: "https://summerofcode.withgoogle.com/",
    description: "Global open-source development program connecting contributors with mentoring organizations.",
    location: "Global / Remote",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://summerofcode.withgoogle.com/" }
  },
  {
    id: "opp_2026_023",
    title: "Hacktoberfest",
    type: "Open Source Program",
    organization: "DigitalOcean",
    tags: ["Open Source", "GitHub", "Community", "Students"],
    deadline: "October annual event",
    apply_link: "https://hacktoberfest.com/",
    description: "Annual open-source contribution event encouraging developers to contribute to participating repositories.",
    location: "Global / Online",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://hacktoberfest.com/" }
  },
  {
    id: "opp_2026_024",
    title: "GirlScript Summer of Code",
    type: "Open Source Program",
    organization: "GirlScript Foundation",
    tags: ["Open Source", "Students", "Mentorship", "India"],
    deadline: "Annual program",
    apply_link: "https://gssoc.girlscript.tech/",
    description: "Open-source contribution program designed to help students gain practical development experience.",
    location: "India / Remote",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://gssoc.girlscript.tech/" }
  },
  {
    id: "opp_2026_025",
    title: "Smart India Hackathon",
    type: "Hackathon",
    organization: "Ministry of Education, Government of India",
    tags: ["Hackathon", "Innovation", "India", "Students"],
    deadline: "Annual cycle",
    apply_link: "https://www.sih.gov.in/",
    description: "National student innovation and problem-solving hackathon focused on real-world challenges.",
    location: "India",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.sih.gov.in/" }
  },
  {
    id: "opp_2026_026",
    title: "National Scholarship Portal",
    type: "Scholarship",
    organization: "Government of India",
    tags: ["Scholarship", "India", "Students", "Financial Aid"],
    deadline: "Varies by scheme",
    apply_link: "https://scholarships.gov.in/",
    description: "Government portal for multiple central and state scholarship schemes for eligible students.",
    location: "India",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://scholarships.gov.in/" }
  },
  {
    id: "opp_2026_027",
    title: "AICTE Pragati Scholarship",
    type: "Scholarship",
    organization: "AICTE",
    tags: ["Scholarship", "Women in STEM", "Engineering", "India"],
    deadline: "Annual cycle",
    apply_link: "https://www.aicte-india.org/schemes/students-development-schemes",
    description: "Scholarship scheme supporting eligible girl students pursuing technical education in India.",
    location: "India",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.aicte-india.org/schemes/students-development-schemes" }
  },
  {
    id: "opp_2026_028",
    title: "AICTE Saksham Scholarship",
    type: "Scholarship",
    organization: "AICTE",
    tags: ["Scholarship", "Accessibility", "Engineering", "India"],
    deadline: "Annual cycle",
    apply_link: "https://www.aicte-india.org/schemes/students-development-schemes",
    description: "AICTE scholarship support for eligible specially-abled students pursuing technical education.",
    location: "India",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.aicte-india.org/schemes/students-development-schemes" }
  },
  {
    id: "opp_2026_029",
    title: "Reliance Foundation Scholarship",
    type: "Scholarship",
    organization: "Reliance Foundation",
    tags: ["Scholarship", "Undergraduate", "India", "STEM"],
    deadline: "Annual cycle",
    apply_link: "https://www.reliancefoundation.org/education",
    description: "Higher-education scholarship program supporting talented Indian students subject to the current eligibility criteria.",
    location: "India",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.reliancefoundation.org/education" }
  },
  {
    id: "opp_2026_030",
    title: "Tata Capital Pankh Scholarship",
    type: "Scholarship",
    organization: "Tata Capital",
    tags: ["Scholarship", "Education", "India", "Financial Aid"],
    deadline: "Annual cycle",
    apply_link: "https://www.tatacapital.com/sustainability/education.html",
    description: "Education scholarship initiative supporting eligible students from financially constrained backgrounds.",
    location: "India",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.tatacapital.com/sustainability/education.html" }
  },
  {
    id: "opp_2026_031",
    title: "Internshala Student Internships",
    type: "Internship",
    organization: "Internshala",
    tags: ["Internship", "Students", "India", "Remote"],
    deadline: "Varies by listing",
    apply_link: "https://internshala.com/internships/",
    description: "Directory of internships across software development, data, design, business and other student career tracks.",
    location: "India / Remote",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://internshala.com/internships/" }
  },
  {
    id: "opp_2026_032",
    title: "LinkedIn Student Jobs and Internships",
    type: "Internship",
    organization: "LinkedIn",
    tags: ["Internship", "Students", "Jobs", "Career"],
    deadline: "Varies by listing",
    apply_link: "https://www.linkedin.com/jobs/",
    description: "Professional job marketplace with current internship and entry-level listings from employers.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.linkedin.com/jobs/" }
  },
  {
    id: "opp_2026_033",
    title: "Wellfound Startup Jobs",
    type: "Internship",
    organization: "Wellfound",
    tags: ["Startups", "Internship", "Software", "Remote"],
    deadline: "Varies by listing",
    apply_link: "https://wellfound.com/jobs",
    description: "Startup-focused jobs marketplace with engineering, product, design and other opportunities.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://wellfound.com/jobs" }
  },
  {
    id: "opp_2026_034",
    title: "Google Careers Internships",
    type: "Internship",
    organization: "Google",
    tags: ["Software Engineering", "AI", "Internship", "Students"],
    deadline: "Varies by listing",
    apply_link: "https://www.google.com/about/careers/applications/students/",
    description: "Official Google student careers portal for internships, apprenticeships and student opportunities.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.google.com/about/careers/applications/students/" }
  },
  {
    id: "opp_2026_035",
    title: "Microsoft University Internships",
    type: "Internship",
    organization: "Microsoft",
    tags: ["Software Engineering", "AI", "Cloud", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://careers.microsoft.com/v2/global/en/students",
    description: "Official Microsoft student careers portal covering internships and early-career technology roles.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://careers.microsoft.com/v2/global/en/students" }
  },
  {
    id: "opp_2026_036",
    title: "Amazon Student Programs",
    type: "Internship",
    organization: "Amazon",
    tags: ["Software Engineering", "Cloud", "Internship", "Students"],
    deadline: "Varies by listing",
    apply_link: "https://www.amazon.jobs/content/en/job-categories/university",
    description: "Amazon university careers portal with internships and graduate opportunities across technical and business roles.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.amazon.jobs/content/en/job-categories/university" }
  },
  {
    id: "opp_2026_037",
    title: "Adobe University Programs",
    type: "Internship",
    organization: "Adobe",
    tags: ["Software", "Design", "AI", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://www.adobe.com/careers/students.html",
    description: "Adobe student careers portal for internships and early-career opportunities in technology and creative software.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.adobe.com/careers/students.html" }
  },
  {
    id: "opp_2026_038",
    title: "Intel Student and Graduate Opportunities",
    type: "Internship",
    organization: "Intel",
    tags: ["Semiconductors", "AI", "Software", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://jobs.intel.com/",
    description: "Intel careers portal with student, internship and early-career roles across engineering and technology.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://jobs.intel.com/" }
  },
  {
    id: "opp_2026_039",
    title: "NVIDIA University Recruiting",
    type: "Internship",
    organization: "NVIDIA",
    tags: ["AI", "GPU", "Software", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://www.nvidia.com/en-us/about-nvidia/careers/",
    description: "NVIDIA careers portal with university and early-career opportunities in software, hardware and AI.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.nvidia.com/en-us/about-nvidia/careers/" }
  },
  {
    id: "opp_2026_040",
    title: "Cisco Early Careers",
    type: "Internship",
    organization: "Cisco",
    tags: ["Networking", "Software", "Cybersecurity", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://jobs.cisco.com/",
    description: "Cisco careers portal for internships and early-career positions across networking and technology.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://jobs.cisco.com/" }
  },
  {
    id: "opp_2026_041",
    title: "IBM Early Professional Careers",
    type: "Internship",
    organization: "IBM",
    tags: ["AI", "Cloud", "Software", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://www.ibm.com/careers",
    description: "IBM careers portal with internship, apprenticeship and early-professional technology roles.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.ibm.com/careers" }
  },
  {
    id: "opp_2026_042",
    title: "Salesforce Futureforce",
    type: "Internship",
    organization: "Salesforce",
    tags: ["Software", "Cloud", "Internship", "Students"],
    deadline: "Varies by listing",
    apply_link: "https://www.salesforce.com/company/careers/university/",
    description: "Salesforce university recruiting program for internships and early-career opportunities.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.salesforce.com/company/careers/university/" }
  },
  {
    id: "opp_2026_043",
    title: "JPMorganChase Student Programs",
    type: "Internship",
    organization: "JPMorganChase",
    tags: ["Software", "Finance", "Data", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://www.jpmorganchase.com/careers/students",
    description: "Student careers portal covering technology, data, finance and other internship programs.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.jpmorganchase.com/careers/students" }
  },
  {
    id: "opp_2026_044",
    title: "Morgan Stanley Students and Graduates",
    type: "Internship",
    organization: "Morgan Stanley",
    tags: ["Technology", "Finance", "Data", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://www.morganstanley.com/people-opportunities/students-graduates",
    description: "Student and graduate careers portal with technology and financial-services internship opportunities.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.morganstanley.com/people-opportunities/students-graduates" }
  },
  {
    id: "opp_2026_045",
    title: "Goldman Sachs Student Programs",
    type: "Internship",
    organization: "Goldman Sachs",
    tags: ["Technology", "Finance", "Data", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://www.goldmansachs.com/careers/students",
    description: "Official student careers portal for internships and early-career opportunities.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.goldmansachs.com/careers/students" }
  },
  {
    id: "opp_2026_046",
    title: "Meta University and Early Careers",
    type: "Internship",
    organization: "Meta",
    tags: ["Software", "AI", "Data", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://www.metacareers.com/jobs/",
    description: "Meta careers portal with internships and early-career opportunities across engineering and technology.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.metacareers.com/jobs/" }
  },
  {
    id: "opp_2026_047",
    title: "GitLab Remote Internship and Early Careers",
    type: "Internship",
    organization: "GitLab",
    tags: ["Remote", "Software", "DevOps", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://about.gitlab.com/jobs/",
    description: "GitLab careers portal with remote-first opportunities and early-career roles when available.",
    location: "Remote / Global",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://about.gitlab.com/jobs/" }
  },
  {
    id: "opp_2026_048",
    title: "Atlassian Early Careers",
    type: "Internship",
    organization: "Atlassian",
    tags: ["Software", "Cloud", "Product", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://www.atlassian.com/company/careers/students",
    description: "Atlassian student careers resources and early-career technology opportunities.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.atlassian.com/company/careers/students" }
  },
  {
    id: "opp_2026_049",
    title: "SAP Student and Graduate Careers",
    type: "Internship",
    organization: "SAP",
    tags: ["Software", "Cloud", "Data", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://www.sap.com/about/careers/students-graduates.html",
    description: "SAP student and graduate careers portal covering internships, working-student roles and early careers.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.sap.com/about/careers/students-graduates.html" }
  },
  {
    id: "opp_2026_050",
    title: "Accenture Student and Graduate Careers",
    type: "Internship",
    organization: "Accenture",
    tags: ["Technology", "Consulting", "AI", "Internship"],
    deadline: "Varies by listing",
    apply_link: "https://www.accenture.com/in-en/careers/life-at-accenture/students",
    description: "Student careers portal with technology, consulting and digital internship and graduate opportunities.",
    location: "Global / Varies",
    isLive: true,
    verificationDetails: { isVerified: true, verifiedBy: "YuvaHub Audit Team", verifiedAt: "2026-08-15", auditSourceUrl: "https://www.accenture.com/in-en/careers/life-at-accenture/students" }
  }
];
